# Generated by Django 5.2.8 on 2025-11-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(help_text='código de barras del producto (EAN-13)', max_length=13, unique=True, verbose_name='código de barras')),
                ('nombre', models.CharField(help_text='nombre completo del producto', max_length=200, verbose_name='nombre del producto')),
                ('descripcion', models.TextField(blank=True, help_text='descripción del producto', null=True, verbose_name='descripción')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='precio del proveedor', max_digits=10, verbose_name='precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='precio para el cliente', max_digits=10, verbose_name='precio de venta')),
                ('stock', models.PositiveIntegerField(default=0, help_text='cantidad de productos en el inventario', verbose_name='stock disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='cantidad mínima para volver a ordenar', verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True, help_text='¿sigue disponible para venta?', verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de última actualización')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos_producto',
                'ordering': ['nombre'],
            },
        ),
    ]
