# Generated by Django 5.2.8 on 2025-11-17 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='fecha y hora de la venta', verbose_name='fecha de venta')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='monto de la venta', max_digits=10, verbose_name='total de la venta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='estado de la venta', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, help_text='observaciones o notas de la venta', null=True, verbose_name='notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de unidades vendidas', verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad al momento de la venta', max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='total de la cantidad por c/u', max_digits=10, verbose_name='subtotal')),
                ('producto', models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='productos.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(help_text='Venta a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalles de la venta',
                'db_table': 'ventas_detalleventa',
            },
        ),
    ]
