# Generated by Django 5.2.8 on 2025-11-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagen del producto', null=True, upload_to='productos/', verbose_name='imagen del producto'),
        ),
    ]
