# Generated by Django 5.2.8 on 2025-12-15 15:42

import productos.image_utils
import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='productos/thumbnails/', verbose_name='miniatura'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagen del producto (máx 5MB)', null=True, upload_to=productos.models.upload_to_productos, validators=[productos.image_utils.validate_image_size, productos.image_utils.validate_image_format, productos.image_utils.validate_image_dimensions], verbose_name='imagen del producto'),
        ),
    ]
