# Generated by Django 6.0 on 2025-12-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_imagen_thumbnail_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='impuesto al valor agregado', max_digits=10, verbose_name='IVA (16%)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='total sin IVA', max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='subtotal + IVA', max_digits=10, verbose_name='total de la venta'),
        ),
    ]
