# Generated by Django 5.2.8 on 2025-11-23 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Permiso')),
                ('modulo', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('cocina', 'Cocina'), ('reportes', 'Reportes'), ('configuracion', 'Configuración'), ('usuarios', 'Usuarios')], max_length=50, verbose_name='Módulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'codigo'],
                'indexes': [models.Index(fields=['codigo'], name='permisos_codigo_111d3c_idx'), models.Index(fields=['modulo'], name='permisos_modulo_b603c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_sistema', models.BooleanField(default=False, verbose_name='Rol del Sistema')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='persistence.permiso')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Username')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Password Hash')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='persistence.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Token')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to='persistence.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'db_table': 'tokens_recuperacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='IntentosLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=255, verbose_name='Email/Username Intentado')),
                ('exitoso', models.BooleanField(default=False, verbose_name='Exitoso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Intento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_login', to='persistence.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'db_table': 'intentos_login',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('activar', 'Activar'), ('desactivar', 'Desactivar'), ('cambiar_rol', 'Cambiar Rol'), ('cambiar_password', 'Cambiar Password')], max_length=50, verbose_name='Acción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='persistence.usuario', verbose_name='Usuario')),
                ('usuario_modificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to='persistence.usuario', verbose_name='Modificado Por')),
            ],
            options={
                'verbose_name': 'Auditoría de Usuario',
                'verbose_name_plural': 'Auditorías de Usuarios',
                'db_table': 'auditoria_usuarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='usuarios_usernam_7abab6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='usuarios_is_acti_8ee55c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenrecuperacion',
            index=models.Index(fields=['token'], name='tokens_recu_token_dd470c_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenrecuperacion',
            index=models.Index(fields=['usado', 'fecha_expiracion'], name='tokens_recu_usado_f61f14_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoslogin',
            index=models.Index(fields=['identificador', 'fecha_intento'], name='intentos_lo_identif_ddcc91_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoslogin',
            index=models.Index(fields=['exitoso'], name='intentos_lo_exitoso_072feb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriausuario',
            index=models.Index(fields=['usuario', 'fecha'], name='auditoria_u_usuario_5b94b7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriausuario',
            index=models.Index(fields=['accion'], name='auditoria_u_accion_aea471_idx'),
        ),
    ]
